### ISSUE TITLE
UNKNOWN_OPTION: Unknown option: -T

### ISSUE THREAD

**Issue by pwdelbloomboard** [kbravh/tweet-to-markdown#12]
Hey, sorry I have not gotten back to try out this tool since almost a month ago after you had addressed the last issue, I was busy.

Fairly self-explanatory, the -T flag does not appear to be working.

Wondering if the order of the flag matters?

```
$ ttm -b "TTM>BEARERINFO" https://twitter.com/iotmpls/status/1565387911264075776 -T -a
/Users/username/.config/yarn/global/node_modules/tweet-to-markdown/dist/main.js:2040
        throw err
        ^

UNKNOWN_OPTION: Unknown option: -T
    at commandLineArgs (/Users/username/.config/yarn/global/node_modules/tweet-to-markdown/dist/main.js:2037:21)
    at Object.<anonymous> (/Users/username/.config/yarn/global/node_modules/tweet-to-markdown/dist/main.js:15367:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  optionName: '-T'
}
```

**Comment by kbravh** [comment]
@pwdelbloomboard The `-T` flag was introduced in version 2.1.0, so yarn may be using an older version of the package. You can run `yarn global add tweet-to-markdown@latest` to pull down the new version (comes with the progress counter I mentioned in https://github.com/kbravh/tweet-to-markdown/issues/13). Hope that helps!
