### ISSUE TITLE
Forbidden error when downloading a tweet and having a valid bearer token

### ISSUE THREAD

**Issue by AJCM-git** [kbravh/tweet-to-markdown#23]
Hi, im getting this error when trying to pull a tweet

```
2023-05-07XXXXXXZ: Forbidden; [object Object]
Error: Request failed with status code 403
    at createError (/usr/lib/node_modules/tweet-to-markdown/dist/main.js:7854:15)
    at settle (/usr/lib/node_modules/tweet-to-markdown/dist/main.js:7870:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/tweet-to-markdown/dist/main.js:10226:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

the bearer token should be valid as i just made it and if it was invalid the error would  be Unauthorized, not Forbidden

**Comment by AJCM-git** [comment]
I think its because you cant pull tweets with the free plan, you need the basic one, in which case the documentation needs updating to mention this
![image](https://user-images.githubusercontent.com/60196617/236697964-58e99e1f-1576-497c-8311-00efcff04471.png)

**Comment by kbravh** [comment]
Hi @AJCM-git, thanks for catching that. I've updated the documentation.
